#!/data/data/com.termux/files/usr/bin/sh
set -e -u

SCRIPTNAME=termux-mediastore
show_usage () {
    echo "Usage: $SCRIPTNAME [-d duration] [-f]"
    echo "Search file in mediastore."
    echo "  -i  all the image"
    echo "  -a  all the audio"
    echo "  -v  all the video"
    echo "  -f  type filetype split with :"
    exit 0
}

PARAMS=""

while getopts :hiavf: option
do
    case "$option" in
	h) show_usage;;
	i) PARAMS="$PARAMS ";;
	a) PARAMS="$PARAMS ";;
	v) PARAMS="$PARAMS ";;
	f) PARAMS="$PARAMS --es documents $OPTARG";;
	?) echo "$SCRIPTNAME: illegal option -$OPTARG"; exit 1;
    esac
done
shift $((OPTIND-1))

if [ $# != 0 ]; then echo "$SCRIPTNAME: too many arguments"; exit 1; fi

/data/data/com.termux/files/usr/libexec/termux-api MediaStore $PARAMS
